### ISSUE TITLE
"Could not reach this instance" without even trying

### ISSUE THREAD

**Issue by djagoo** [nextcloud/xwiki#12]
When I try to connect to our xwiki the app instantly reports "Could not reach this instance". When I try to use "https://playground.xwiki.org/xwiki" for example it works without errors.

So I turned on the debug log of our reverseproxy and saw there was no request from nextcloud to xwiki logged. Packet capture shows, that the moment after the DNS request was answered with the correct A record the error occurs without any packet going out from the nextcloud server. When I try the same with the playground url it connects to 443 after getting the DNS A record. So I opened up a terminal session within the nextcloud container and ran curl to the url I used which works without problems. (see screenshots attached)

I'm really out of ideas here. I already disabled https, tried direct connection to the IP without reverseproxy (tried putting them in the same docker network)...

![Screenshot_20230820_101353](https://github.com/nextcloud/xwiki/assets/5556738/2a788a65-da80-4730-9653-a59c481e6e0f)
![Screenshot_20230820_101544](https://github.com/nextcloud/xwiki/assets/5556738/b6d7a2cc-095c-42af-b18b-c43e0724c6e2)

Would be nice if anyone had an idea.

**Comment by raphj** [comment]
Nextcloud might have a protection against allowing access to local IPs. I have this in my Nextcloud config on my dev machine, can you try this in `nexctloud/config/config.php`?

    'allow_local_remote_servers' => true,

Nextcloud the GuzzleHttp HTTP lib, which might need some configuration / have some restrictions, hence the fact you see something works with curl but not in Nextcloud.

Other things to consider / try:

- Could it be some security module like SELinux that prevents php from connecting to local IPs, or something? Have you tried connecting to your XWiki instance from the php cli, under your www-data UNIX user?
- Have you tried connecting to your XWiki instance from a Nextcloud instance outside your network?

**Comment by djagoo** [comment]
You a a genius!

`'allow_local_remote_servers' => true,`

Really did the trick. Thank you so much!
