### ISSUE TITLE
Progress on the integration

### ISSUE THREAD

**Issue by sebastiaanveld** [nextcloud/xwiki#14]
I was wondering is there is any progress on this integration, as it's quite for quite some time. Is this a dead end of will what's here todat be replaced/integrated with[ XWIki 'Cristal'](https://fosdem.org/2024/schedule/event/fosdem-2024-1831-cristal-a-new-wiki-ui-to-rule-them-all/)? 

Thx!

**Comment by sebastiaanveld** [comment]
Hi @raphj,

Would love to be at Fosdem and meet all of you, but unfortunately time not does permit me be there:/

I'll try to post some new issues I run into with the NC XWiki integration, but most of what I run into is already here and that's restricting it from being usefull. Hope you find so time once to work on these:)

THX!

King regards, Sebastiaan

**Comment by manuelleduc** [comment]
Hello @sebastiaanveld,

FOSDEM is also broadcasted live (and the videos available later as well). 
Feel free to chat with us during the event through FOSDEM online chat or on our matrix chat later on (https://riot.im/app/#/room/#xwiki:matrix.xwiki.com).

**Comment by sebastiaanveld** [comment]
Thx @manuelleduc, following certain sessions online is on my planning list:)
Have fun over there!
