### ISSUE TITLE
Non admin users can't get access to XWiki

### ISSUE THREAD

**Issue by raphj** [nextcloud/xwiki#6]
Non admin users get "access forbidden" when clicking on Get access.

![image](https://user-images.githubusercontent.com/3817365/229559528-4d9690ba-05c1-44a7-bffd-0ec020d19970.png)

**Comment by raphj** [comment]
We are working on improving this part. XWiki is going to suggest you to login in such a case where you are not already logged. For now you need to login on XWiki indeed. However, the "access forbidden" screen from Nextcloud is Nextcloud blocking the request, there's probably a way to tell Nextcloud that the `settings/requestToken`  is allowed to simple users

**Comment by raphj** [comment]
@sebastiaanveld I've just released a new version with a fix for this issue. Let me know if you manage to get access with a non-admin user.

**Comment by sebastiaanveld** [comment]
With the updates app a get a step futher, after landing on the Xxiki token page, I login and select to agree to let NC logon for the user, then i get this error:

![image](https://user-images.githubusercontent.com/37268999/229591414-8e2657df-3f92-4239-86a7-752fbe4043f2.png)

**Comment by raphj** [comment]
Indeed, thanks. This was an overlook on the XWiki extension. For reference: https://jira.xwiki.org/browse/NEXTCLOUD-5.

I just released a version containing a fix for this issue, please upgrade the "Nextcloud Application" extension in XWiki and let me know if it works.

**Comment by sebastiaanveld** [comment]
Thx, this looks fixed.

**Comment by raphj** [comment]
Nice! Thanks for the debugging session.
